# Generated by Django 5.2.7 on 2025-10-19 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payement_id',
            new_name='payment_id',
        ),
    ]
