# Generated by Django 5.2.7 on 2025-10-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_payement_id_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='boarding_location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passenger',
            name='dropping_location',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
