# Generated by Django 5.2.7 on 2025-10-24 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_payment_refund_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_date',
            field=models.DateField(default=datetime.date(2025, 10, 24)),
        ),
    ]
