# Generated by Django 5.2.7 on 2025-10-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_booking_booked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
