# Generated by Django 5.2.7 on 2025-10-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_alter_trip_arrival_time_alter_trip_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('CONFIRMED', 'confirmed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='CONFIRMED', max_length=20),
        ),
    ]
