# Generated by Django 5.2.7 on 2025-10-27 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='is_booked',
        ),
    ]
