# Generated by Django 5.2.7 on 2025-10-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_remove_seat_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
