# Generated by Django 5.2.7 on 2025-10-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_booking_payment_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='layout_type',
            field=models.CharField(choices=[('2*2', '2*2 Seating'), ('1*2', '1*2 seating'), ('Sleeper', 'Sleeper Layout')], default='default', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='operator_mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_type',
            field=models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC'), ('Sleeper', 'sleeper')], max_length=50),
        ),
    ]
