# Generated by Django 5.2.7 on 2025-10-28 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_alter_payment_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(help_text='The order of this stop in the  route')),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('distance_from_start', models.FloatField(blank=True, help_text='Distance in km from start', null=True)),
                ('fare_from_start', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='bookings.route')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
