# Generated by Django 5.2.7 on 2025-10-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_routestop'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='fare',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
