# Generated by Django 5.2.7 on 2025-10-28 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_passenger_fare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routestop',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='routestop',
            name='departure_time',
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField()),
                ('route_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.routestop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_stops', to='bookings.trip')),
            ],
            options={
                'ordering': ['route_stop__order'],
            },
        ),
    ]
