# Generated by Django 5.2.7 on 2025-10-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_remove_routestop_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='gender_preference',
            field=models.CharField(choices=[('ANY', 'Any'), ('WOMEN_ONLY', 'Women only')], default='ANY', max_length=10),
        ),
    ]
