# Generated by Django 5.2.7 on 2025-10-30 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_seat_gender_preference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='operator_mobile_no',
            new_name='operator_mobile',
        ),
    ]
