# Generated by Django 5.2.7 on 2025-10-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_rename_operator_mobile_no_bus_operator_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routestop',
            name='fare_from_start',
        ),
        migrations.AddField(
            model_name='tripstop',
            name='fare_from_start',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
