# Generated by Django 5.2.7 on 2025-10-30 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_remove_routestop_fare_from_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripstop',
            name='arrival_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
