# Generated by Django 5.2.7 on 2025-11-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_alter_tripstop_arrival_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='roundtrip_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
