# Generated by Django 5.2.7 on 2025-11-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_booking_roundtrip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='layout_type',
            field=models.CharField(choices=[('2*2', '2*2 Seating'), ('2*3', '2*3 Seating'), ('Sleeper', 'Sleeper Layout')], max_length=20),
        ),
    ]
