# Generated by Django 5.2.7 on 2025-11-18 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_alter_bus_layout_type'),
        ('users', '0002_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='operator_mobile',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='operator_name',
        ),
        migrations.AddField(
            model_name='trip',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='users.operator'),
        ),
    ]
