# Generated by Django 5.2.7 on 2025-11-20 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0026_remove_bus_operator_mobile_remove_bus_operator_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='departure_time',
        ),
        migrations.AddField(
            model_name='trip',
            name='arrival',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 20, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='departure',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 20, 0, 0)),
            preserve_default=False,
        ),
    ]
