# Generated by Django 5.2.7 on 2025-11-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0027_remove_trip_arrival_time_remove_trip_departure_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_type',
            field=models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC')], max_length=50),
        ),
    ]
